export const aboutMatter = [
    "Comity Edutech Services Pvt. Ltd is the leading education advisory and consultancy service in Jaipur , (Rajasthan) and operational since year 2010 as a partnership firm. Comity Edutech was  incorporated as a Private Limited Company in year 2015 with a Vision  of becoming an Indian Originated Project Management Agency in near future.",
    "Facilitated by our expert team of professionals, we guide our clients through discovery of business drivers, desired project approval process, and team & organization structure as well.",
    "From this, we consider an optimized delivery structure. We capture critical success factors and desired business outcomes to best understand the type of techniques suited to the organization.",
    "We have utilized our project management expertise  for many of our clients, providing recommendations for continual improvements.  This has led to increased maturity, or in some cases project  transformation, to align to business dynamics.",
    "Briefing about our role in education sector, our knowledge and expertise helps us support and advise families to reach their maximum potential and to gain access to the very best of education. Our business is built on the quality and integrity of our people with close links to admissions offices, Head’s and the most influential senior figures within the education industry. We are proud to offer expert advice that puts your child at the center of the process.",
    "Our Purpose- ‘Harmony for Excellence’, we’re committed to providing our people with an opportunity that opens many possibilities for them to meet their career and personal developmental goals.",
    "Comity Edutech also deals in skill development programs by supporting individuals from all communities through a range of inclusive programs, to increase their work-based and employability skills, enabling them to take their first steps into the labor market, or to make successful career change and progression.",
    "Comity also works directly with employers, providing trusted advice that helps employers invest in existing skills, develop new talent using equal and inclusive recruitment, and get the right products to enhance their business ensure mutual development for both the parties.",
    "Build a career with us ->",
    "As a leading Project management & education consultancy and advisory service we are always delighted to hear from leaders in their field across all spectrums.",
    "We are always interested in speaking to experienced and passionate education professionals across all sectors.  If you feel you may be able to offer value to our families around the world and the job is not listed about, we are always keen to hear from talented professionals in their field so please get in touch in complete confidence.",
]